// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing feeding suggestions to pig farmers.
 *
 * - `getFeedingSuggestion` - A function that takes pig data and returns a feeding suggestion.
 * - `FeedingSuggestionInput` - The input type for the `getFeedingSuggestion` function.
 * - `FeedingSuggestionOutput` - The return type for the `getFeedingSuggestion` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FeedingSuggestionInputSchema = z.object({
  pigAge: z.number().describe('Age of the pig in weeks.'),
  pigWeight: z.number().describe('Weight of the pig in kilograms.'),
  pigBreed: z.string().describe('Breed of the pig.'),
  currentFeed: z.string().describe('Current feed being given to the pig.'),
  environmentalConditions: z
    .string()
    .describe('Description of the environmental conditions where the pig is kept.'),
});
export type FeedingSuggestionInput = z.infer<typeof FeedingSuggestionInputSchema>;

const FeedingSuggestionOutputSchema = z.object({
  suggestedFeedType: z.string().describe('Recommended feed type for the pig.'),
  suggestedFeedQuantity: z
    .string()
    .describe('Recommended quantity of feed to give the pig per day.'),
  additionalRecommendations: z
    .string()
    .describe('Any additional recommendations for improving pig health and growth.'),
});
export type FeedingSuggestionOutput = z.infer<typeof FeedingSuggestionOutputSchema>;

export async function getFeedingSuggestion(input: FeedingSuggestionInput): Promise<FeedingSuggestionOutput> {
  return feedingSuggestionFlow(input);
}

const feedingSuggestionPrompt = ai.definePrompt({
  name: 'feedingSuggestionPrompt',
  input: {schema: FeedingSuggestionInputSchema},
  output: {schema: FeedingSuggestionOutputSchema},
  prompt: `You are an expert in pig farming and nutrition. Based on the provided information, provide optimal feeding suggestions.

Pig Age: {{pigAge}} weeks
Pig Weight: {{pigWeight}} kg
Pig Breed: {{pigBreed}}
Current Feed: {{currentFeed}}
Environmental Conditions: {{environmentalConditions}}

Provide the following:
- Suggested Feed Type: The most suitable feed type for this pig.
- Suggested Feed Quantity: The recommended quantity of feed per day.
- Additional Recommendations: Any other advice to improve growth, reduce waste, and prevent illnesses.

Ensure the suggestions are practical and actionable for the farmer.
`,
});

const feedingSuggestionFlow = ai.defineFlow(
  {
    name: 'feedingSuggestionFlow',
    inputSchema: FeedingSuggestionInputSchema,
    outputSchema: FeedingSuggestionOutputSchema,
  },
  async input => {
    const {output} = await feedingSuggestionPrompt(input);
    return output!;
  }
);
