// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing feeding suggestions to pig farmers.
 *
 * - `getFeedingSuggestion` - A function that takes pig data and returns a feeding suggestion.
 * - `FeedingSuggestionInput` - The input type for the `getFeedingSuggestion` function.
 * - `FeedingSuggestionOutput` - The return type for the `getFeedingSuggestion` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FeedingSuggestionInputSchema = z.object({
  pigAge: z.number().describe('Edad del cerdo en semanas.'),
  pigWeight: z.number().describe('Peso del cerdo en kilogramos.'),
  pigBreed: z.string().describe('Raza del cerdo.'),
  currentFeed: z.string().describe('Alimento actual que se le da al cerdo.'),
  environmentalConditions: z
    .string()
    .describe('Descripción de las condiciones ambientales donde se mantiene al cerdo.'),
});
export type FeedingSuggestionInput = z.infer<typeof FeedingSuggestionInputSchema>;

const FeedingSuggestionOutputSchema = z.object({
  suggestedFeedType: z.string().describe('Tipo de alimento recomendado para el cerdo.'),
  suggestedFeedQuantity: z
    .string()
    .describe('Cantidad de alimento recomendada para dar al cerdo por día.'),
  additionalRecommendations: z
    .string()
    .describe('Cualquier recomendación adicional para mejorar la salud y el crecimiento del cerdo.'),
});
export type FeedingSuggestionOutput = z.infer<typeof FeedingSuggestionOutputSchema>;

export async function getFeedingSuggestion(input: FeedingSuggestionInput): Promise<FeedingSuggestionOutput> {
  return feedingSuggestionFlow(input);
}

const feedingSuggestionPrompt = ai.definePrompt({
  name: 'feedingSuggestionPrompt',
  input: {schema: FeedingSuggestionInputSchema},
  output: {schema: FeedingSuggestionOutputSchema},
  prompt: `Eres un experto en porcicultura y nutrición porcina. Basado en la información proporcionada, ofrece sugerencias de alimentación óptimas.

Edad del Cerdo: {{pigAge}} semanas
Peso del Cerdo: {{pigWeight}} kg
Raza del Cerdo: {{pigBreed}}
Alimento Actual: {{currentFeed}}
Condiciones Ambientales: {{environmentalConditions}}

Proporciona lo siguiente:
- Tipo de Alimento Sugerido: El tipo de alimento más adecuado para este cerdo.
- Cantidad de Alimento Sugerida: La cantidad recomendada de alimento por día.
- Recomendaciones Adicionales: Cualquier otro consejo para mejorar el crecimiento, reducir el desperdicio y prevenir enfermedades.

Asegúrate de que las sugerencias sean prácticas y accionables para el granjero.
`,
});

const feedingSuggestionFlow = ai.defineFlow(
  {
    name: 'feedingSuggestionFlow',
    inputSchema: FeedingSuggestionInputSchema,
    outputSchema: FeedingSuggestionOutputSchema,
  },
  async input => {
    const {output} = await feedingSuggestionPrompt(input);
    return output!;
  }
);
