// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for providing presumptive veterinary diagnoses for pigs.
 *
 * - `getPigDiagnosis` - A function that takes clinical data and returns a presumptive diagnosis.
 * - `PigDoctorInput` - The input type for the `getPigDiagnosis` function.
 * - `PigDoctorOutput` - The return type for the `getPigDiagnosis` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PigDoctorInputSchema = z.object({
  symptoms: z.string().describe('Descripción detallada de los síntomas clínicos y cualquier otra observación relevante sobre el animal y su entorno.'),
  photoDataUri: z.string().optional().describe(
      "Una foto del cerdo o de los signos clínicos, como un data URI que debe incluir un tipo MIME y usar codificación Base64. Formato esperado: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type PigDoctorInput = z.infer<typeof PigDoctorInputSchema>;

const DiagnosisSchema = z.object({
    diseaseName: z.string().describe('Nombre de la enfermedad más probable.'),
    probability: z.number().describe('Porcentaje de probabilidad estimado para este diagnóstico (0-100).'),
    justification: z.string().describe('Justificación del diagnóstico basada en los datos proporcionados.'),
});

const PigDoctorOutputSchema = z.object({
  presumptiveDiagnosis: DiagnosisSchema,
  differentialDiagnoses: z.array(DiagnosisSchema).describe('Al menos 3 diagnósticos diferenciales con su probabilidad.'),
  recommendedTreatment: z.object({
    medication: z.string().describe('Fármaco, dosis, vía, frecuencia y duración recomendada.'),
    complementaryMeasures: z.string().describe('Medidas adicionales como hidratación, manejo, bioseguridad, etc.'),
    withdrawalPeriod: z.string().describe('Período de retiro del medicamento sugerido.'),
  }),
  riskLevel: z.enum(['Individual', 'Alerta', 'Brote Potencial']).describe('Clasificación del riesgo sanitario del caso.'),
  operationalRecommendations: z.array(z.string()).describe('Recomendaciones operativas claras y accionables. Ej: "Aislar animales afectados".'),
});
export type PigDoctorOutput = z.infer<typeof PigDoctorOutputSchema>;


export async function getPigDiagnosis(input: PigDoctorInput): Promise<PigDoctorOutput> {
  return pigDoctorFlow(input);
}

const pigDoctorPrompt = ai.definePrompt({
  name: 'pigDoctorPrompt',
  input: {schema: PigDoctorInputSchema},
  output: {schema: PigDoctorOutputSchema},
  prompt: `Eres "PigDoctor", un asistente veterinario experto en porcicultura, entrenado con el Manual Merck, guías de la FAO y la OIE. Tu propósito es emitir diagnósticos presuntivos y sugerir tratamientos. NUNCA debes reemplazar el criterio de un médico veterinario profesional.

Analiza los siguientes datos clínicos de un caso:
- Síntomas y Observaciones: {{symptoms}}
{{#if photoDataUri}}
- Fotografía: {{media url=photoDataUri}}
{{/if}}

Basado en esta información, proporciona un análisis estructurado. La justificación debe ser técnica y concisa. Las recomendaciones deben ser prácticas para un entorno de granja. Si en los síntomas se menciona que hay más de un caso similar, eleva el nivel de riesgo a "Alerta" o "Brote Potencial" según la gravedad y los síntomas.

Siempre finaliza tus recomendaciones indicando que "Este es un diagnóstico presuntivo y debe ser validado por un médico veterinario".
`,
});

const pigDoctorFlow = ai.defineFlow(
  {
    name: 'pigDoctorFlow',
    inputSchema: PigDoctorInputSchema,
    outputSchema: PigDoctorOutputSchema,
  },
  async input => {
    const {output} = await pigDoctorPrompt(input);
    return output!;
  }
);
