// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  "projectId": "smartpig-lite",
  "appId": "1:487539621018:web:e483d82354ac0d9eea3323",
  "storageBucket": "smartpig-lite.firebasestorage.app",
  "apiKey": "AIzaSyD3TdAFwymZzevFIIKopTd4FMQ4ZXcjDiU",
  "authDomain": "smartpig-lite.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "487539621018"
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const auth = getAuth(app);

export { app, auth };
