// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getAuth } from "firebase/auth";
import { getDatabase } from "firebase/database";

const firebaseConfig = {
    apiKey: "AIzaSyD3TdAFwymZzevFIIKopTd4FMQ4ZXcjDiU",
    authDomain: "smartpig-lite.firebaseapp.com",
    projectId: "smartpig-lite",
    storageBucket: "smartpig-lite.appspot.com",
    messagingSenderId: "487539621018",
    appId: "1:487539621018:web:e483d82354ac0d9eea3323",
    measurementId: ""
};


// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getDatabase(app);

export { app, auth, db };
